config/routes.rb
Rails.application.routes.draw do
  root "artists#index"

  resources :songs

  get "/songs/play/:id", to: "songs#play_song", as: "play_song"
  get "/top10songs", to: "songs#top_10_songs", as: "top10_songs"

  resources :artists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
    
    # name is required
    validates :name, presence: true
    
    # bio has a max length of 8000
    validates_presence_of :bio
    validates :bio, length: {maximum: 8000}

    # or:
    #validates :bio, presence: true, length: {maximum:8000}
end

app/models/play_count.rb
class PlayCount < ApplicationRecord
  belongs_to :song
  
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :play_count
  scope :top10, ->{
    select("songs.id, songs.name, artist_id, count(play_counts.id) AS play_count").
    joins(:play_count).
    joins(:artist).
    group("songs.id").
    order("play_count DESC").
    limit(10)
  }

  validates :name, presence: true
  validates :duration, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    # @artist set by the set_artist method
    @songs = @artist.songs
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :bio, :genre)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  # before_action :set_color_scheme, only: [:show, :edit] # Moved to Song Helper

  # Retrieves Top 10 Songs played
  def top_10_songs
    # @play_count = PlayCount.all.group(:song_id).count #.order("count_all desc")
    # @play_count.each { |song_id, count|
    #   p song_id
    # }
    @songs = Song.top10
    # p @play_count
    # p @play_count.inspect
  end

  # Play a Song
  def play_song
    set_song
    # set_color_scheme
    @play_count = PlayCount.new
    @play_count.song = @song
    @play_count.save
    
    # p @play_count

    # Pat's solution
    # Model.find_by - Selects the first one
    # Model.where - Selects all
    # Find existing play count record for this song, if it exists
    # play_count = PlayCount.find_by(song: @song)
    # # Never been played if there is no play count record yet
    # if play_count == nil
    #   # Create play count in the database for this song
    #   play_count = PlayCount.new(song: @song, count: 1)
    #   # Save to database
    #   play_count.save
    # else
    #   # Increment that play count's count value
    #   play_count.count += 1
    #   # Save to database
    #   play_count.save
    # end
    #
    # In model:
    # has_one: play_count # Better way
    #
    # In view:
    # <%= @song.play_count.count %>
  end

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # # Set page color scheme
    # def set_color_scheme
      
    #   # Color Scheme Variable
    #   @color_scheme = ""

    #   @song = Song.find(params[:id])
    #   year_category = @song.released_at.strftime("%Y")

    #   if year_category.starts_with?("198")
    #     @color_scheme = "eightees"

    #   elsif year_category.starts_with?("199")
    #     @color_scheme = "ninetees"

    #   elsif year_category.starts_with?("20")
    #     @color_scheme = "two_thousands"

    #   else
    #     @color_scheme = "default"

    #   end

    # end

    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :artist_id, :duration, :released_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper

    # Format e.g. 127 as 2:07
    # 89 as 1:29
    # 127 as 2:07
    def format_duration(seconds)
        mm = seconds / 60
        ss = '%02d' % (seconds % 60)
        "#{mm}:#{ss}"
    end

    def format_color_scheme(released_at)
        year_category = released_at.year
        
        if year_category >= 2000
            "two_thousands"
        elsif year_category >= 1990
            "ninetees"
        elsif year_category >= 1980
            "eightees"
        else
            "default"
        end
    end

end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :artist_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :artist_bio %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, id: :artist_genre %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"default" %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<nav>
<%= link_to "<button>Show Info</button>".html_safe, @artist %>
<%= link_to "<button>Back</button>".html_safe, artists_path %>
</nav>

app/views/artists/index.html.erb
<h1>Artists</h1>
<p id="notice"><%= notice %></p>

<% @artists.each do |artist| %>
  <div class="artists">
    <h2><%= link_to artist.name, artist %></h2>
    <p><%= artist.genre %> | <%= link_to "#{artist.songs.count} Songs", artist %> |
    <%= link_to "<button>Edit Info</button>".html_safe, edit_artist_path(artist) %>
    <%= link_to "<button>Remove Artist</button>".html_safe, artist, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>

<br>

<nav>
  <%= link_to "<button>Add New Artist</button>".html_safe, new_artist_path %>
  <%= link_to "<button>Show All Songs</button>".html_safe, songs_path %>
  <%= link_to "<button>Show Top 10</button>".html_safe, top10_songs_url %>
</nav>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<nav>
<%= link_to "<button>Back to Artists</button>".html_safe, artists_path %>
</nav>

app/views/artists/show.html.erb
<h1>
  <%= @artist.name %>
</h1>

<div class="artists">
    <p id="notice"><%= notice %></p>
    
<p>
  <strong>Bio:</strong>
  <%= @artist.bio %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @artist.genre %>
</p>

<h2>Songs</h2>
<% @songs.each do |song| %>
  <p><%= link_to song.name, song %></p>
<% end %>
</div>

<nav>
  <%= link_to "<button>Edit Artist Info</button>".html_safe, edit_artist_path(@artist) %>
  <%= link_to "<button>Back</button>".html_safe, artists_path %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotlify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :song_name %>
  </div>

  <div class="field">
    <%= form.label :artist_id %>
    <%= form.collection_select :artist_id, Artist.all, :id, :name, id: :song_artist_id, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, id: :song_duration %>
  </div>

  <div class="field">
    <%= form.label :released_at %>
    <%= form.date_select :released_at, id: :song_released_at, start_year: 1900 %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: song.released_at.nil? ? format_color_scheme(0) : format_color_scheme(song.released_at) %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1 class="<%= format_color_scheme @song.released_at %>">Editing Song</h1>

<%= render 'form', song: @song %>

<nav>
    <%= link_to "<button class=\"#{format_color_scheme @song.released_at}\">Show Song</button>".html_safe, @song %>
    <%= link_to "<button class=\"#{format_color_scheme @song.released_at}\">Back</button>".html_safe, songs_path %>
</nav>

app/views/songs/index.html.erb
<h1>Songs</h1>
<p id="notice"><%= notice %></p>

<table class="songs_table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Duration</th>
      <th>Released at</th>
      <th>Play Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= link_to song.artist.name, song.artist %></td>
        <td><%= format_duration song.duration %></td>
        <td><%= song.released_at %></td>
        <td><%= song.play_count.size %></td>
        <td><%= link_to "<button>Show</button>".html_safe, song %></td>
        <td><%= link_to "<button>Edit</button>".html_safe, edit_song_path(song) %></td>
        <td><%= link_to "<button>Delete</button>".html_safe, song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<nav>
  <%= link_to "<button>Add New Song</button>".html_safe, new_song_path %>
  <%= link_to "<button>Show Top 10</button>".html_safe, top10_songs_url %>
  <%= link_to "<button>Back to Artists</button>".html_safe, artists_path %>
</nav>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<nav>
<%= link_to "<button>Back to Songs</button>".html_safe, songs_path %>
</nav>

app/views/songs/play_song.html.erb
<p id="notice"><%= notice %></p>

<h1 class="<%= format_color_scheme @song.released_at %>">
  Now Playing: <%= @song.name %>
</h1>

<div class="songs">
  <p>
    <strong>Artist:</strong>
    <%= link_to @song.artist.name, @song.artist %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= format_duration @song.duration  %>
  </p>

  <p>
    <strong>Released at:</strong>
    <%= @song.released_at %>
  </p>
</div>

<nav>
  <%= link_to "<button class=\"#{ format_color_scheme @song.released_at }\">Stop Playing</button>".html_safe, songs_path %>
</nav>

app/views/songs/show.html.erb
<h1 class="<%= format_color_scheme @song.released_at %>">
  <%= @song.name %>
</h1>

<div class="songs">
  <p id="notice"><%= notice %></p>
    
  <p>
    <strong>Artist:</strong>
    <%= link_to @song.artist.name, @song.artist %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= format_duration @song.duration  %>
  </p>

  <p>
    <strong>Released at:</strong>
    <%= @song.released_at %>
  </p>
</div>

<nav>
  <%= link_to "<button class=\"#{format_color_scheme @song.released_at}\">Play Song</button>".html_safe, play_song_url(@song) %>
  <%= link_to "<button class=\"#{format_color_scheme @song.released_at}\">Edit Song Info</button>".html_safe, edit_song_path(@song) %>
  <%= link_to "<button class=\"#{format_color_scheme @song.released_at}\">Back</button>".html_safe, songs_path %>
</nav>

app/views/songs/top_10_songs.html.erb
<p id="notice"><%= notice %></p>

<h1>Top 10 Songs</h1>

<div class="songs">
    <% rank = 1 %>
    <% @songs.each do |song| %>
        <h2>#<%= link_to "#{rank} #{song.artist.name} - #{song.name}", song %></h2>
        <p>(Played <%= song.play_count.size %> times)</p>
        <% rank += 1 %>
    <% end %>
</div>

<br>

<nav>
<%= link_to "<button>Back to Artists</button>".html_safe, artists_path %>
</nav>